#!/bin/sh

#
# chkconfig: 345 98 02
# description: CSL server
#
. /etc/rc.d/init.d/functions

SCRIPT="$(basename $0)"

USER="csl-server"
NODE="node"
NODE_DIR="/opt/csl-server"
NODE_APP="$NODE_DIR/src/server.js"
LOG_FILE="/var/log/csl-server/csl-server.log"
COMMAND="$NODE $NODE_APP"

lock_file="/var/lock/subsys/$SCRIPT"

do_start()
{
        if [ ! -f "$lock_file" ] ; then
                echo -n $"Starting $SCRIPT: "
                runuser -l "$USER" -s /bin/sh -c "$COMMAND >> $LOG_FILE &"
                RETVAL=$?
                if [ $RETVAL -eq 0 ]; then
                  touch $lock_file
                  echo_success
                else
                  echo_failure
                fi
                echo
        else
                echo "$SCRIPT is locked."
                RETVAL=1
        fi
}

do_stop()
{
        echo -n $"Stopping $SCRIPT: "
        pkill -9 -fx "$COMMAND" > /dev/null 2>&1
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
          rm -f $lock_file
          echo_success
        else
          echo_failure
        fi
        echo
}

do_status()
{
        PID=`pgrep -fx "$COMMAND"`
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
          echo "$SCRIPT is running"
        else
          echo "$SCRIPT is not running"
        fi
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        status)
                do_status
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|status}"
                RETVAL=1
esac

exit $RETVAL

