#!/bin/sh

#
# chkconfig: 35 99 99
# description: CSL server
#
. /etc/rc.d/init.d/functions

SCRIPT="$(basename $0)"
PID_FILE="/var/run/$SCRIPT.pid"

ps -fe | grep "$SCRIPT" | head -n1 | cut -d" " -f 6 > ${PID_FILE}

USER="csl-server"
NODE="/usr/local/bin/node"
NODE_DIR="/opt/csl-server"
NODE_APP="$NODE_DIR/src/server.js"
LOG_FILE="/var/log/csl-server/csl-server.log"

lock_file="/var/lock/subsys/$SCRIPT"

do_start()
{
        if [ ! -f "$lock_file" ] ; then
                echo -n $"Starting $NODE_APP: "
                runuser -l "$USER" -c "$NODE $NODE_APP >> $LOG_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $lock_file
        else
                echo "$NODE_APP is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $NODE_APP: "
        PID=`ps -fe | grep "$NODE $NODE_APP" | head -n1 | cut -d" " -f 2`
        kill -9 $PID > /dev/null 2>&1 && echo_success || echo_failure
        if [ -f ${PID_FILE} ]; then
        rm ${PID_FILE}
        fi
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lock_file
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL

